plugin: datapipeline
settings:
  datasource: studentcsv
  datadestination: studentsaver
  processors:
    - studentmapper
  pipelinename: studentimportpipeline
  errorprocessor: importerror
  retrysource: importerror
