[package]
name = "laatoocore"
version = "0.1.0"
authors = ["Mandeep Singh Brar <mandeep@virsainfomedia.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
lazy_static="1.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "^0.2.3"
